[features]
seeds = false
skip-lint = false
[programs.devnet]
hackathon = "8mt8v8cLzM8NziTsZTbC7FzVpmZA5fWp297GjjLteWMB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dds-019/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
